---
-
  hosts: '{{ hosts }}'
  gather_facts: false
  connection: local
  vars_files:
    - secrets.yaml

  tasks:
    - name: backup XR
      iosxr_config:
        provider: "{{ credentials }}"
        backup: yes
      when: network_os == 'XR' 
      register: result
    - debug: var=result

    - name: backup XE 
      ios_config: 
        provider: "{{ credentials }}"
        backup: yes  
      when: network_os == 'XE' 
      register: output 
    - debug: var=output 
